id = "turnip_text"
name = "turnip_text"
version = "0.1.0"
schema_version = 1
authors = ["Samuel W. Stark"]
description = "Syntax highlighting and embedded-Python support for turnip_text files."
repository = "https://github.com/theturboturnip/turnip_text_zed"

[grammars.turnip_text]
repository = "https://github.com/theturboturnip/turnip_text_treesitter"
rev = "ade6f689f1b0ab8e46f4768095f34bafa398f5c5"
